# Generated by Django 4.2.4 on 2023-09-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_user_transaction_alter_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_score',
        ),
    ]
