# Generated by Django 4.2.4 on 2023-09-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_user_credit_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
