# Generated by Django 4.2.4 on 2023-09-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_user_aadhar_id_remove_user_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
