# Generated by Django 4.2.4 on 2023-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_user_aadhar_id_user_annual_income_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
    ]
