# Generated by Django 4.2.4 on 2023-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_user_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=500),
        ),
    ]
